use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use n_iter_rs::experiments;
use n_iter_rs::io;

fn main() {
    let quick_mode = env::var("QUICK").is_ok();

    let extract_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap().join("experiments").join("011-fca-n-iteration").join("extracts");
    let output_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap().join("experiments").join("011-fca-n-iteration").join("output");
    let _ = fs::create_dir_all(&output_dir);

    println!("{}", "=".repeat(64));
    println!("  n-iteration experiment suite");
    println!("{}", "=".repeat(64));

    let wiki_extracts = io::load_wikipedia_extracts(&extract_dir);
    println!("Loaded {} Wikipedia extracts", wiki_extracts.len());

    let category_map = io::build_category_map(&wiki_extracts);
    println!("Category map: {} categories", category_map.len());

    experiments::run_experiment(&wiki_extracts, &category_map, &output_dir, quick_mode);

    experiments::param_scan(&wiki_extracts, &category_map, &output_dir);
    experiments::lattice_richness_scan(&wiki_extracts, &category_map, &output_dir);
    experiments::isolation_experiment(&wiki_extracts, &category_map, &output_dir);
    experiments::delta1_scan(&wiki_extracts, &category_map, &output_dir);
    experiments::e1_tokenization_stability(&wiki_extracts, &category_map, &output_dir);
    experiments::e2_carrier_independence(&wiki_extracts, &category_map, &output_dir);
    experiments::degradation_scan(&wiki_extracts, &category_map, &output_dir);
    experiments::theorem_verification(&wiki_extracts, &category_map, &output_dir);

    run_synthetic_suite(&output_dir);
}

fn run_synthetic_suite(output_dir: &PathBuf) {
    println!("{}", "=".repeat(64));
    println!("  synthetic lattice experiment suite");
    println!("{}", "=".repeat(64));

    experiments::run_th617_verification();
    experiments::run_ode_verification();
    experiments::run_ode_stability_analysis();
    experiments::run_lattice_validation_optimal();
    experiments::run_ode_exact_lyapunov();
    experiments::run_convergence_rate_analysis();
    experiments::run_sensitivity_analysis();
    experiments::run_cross_metric_correlation();
    experiments::run_pareto_and_linear_regression();
    experiments::run_cross_regime_pareto();
    experiments::run_beta_delta_2d_sweep();
    experiments::run_super_optimal_characterization();
    experiments::run_fine_grained_landscape();
    experiments::run_tau_mono_phase_diagram();
    experiments::run_n_pred_discrepancy_analysis();
    experiments::run_edge_tau_comparison();
    experiments::run_dstar_dvalue_analysis();
    experiments::run_analytical_dstar();
    experiments::run_bup_propagation();
    experiments::run_rho_analytical();
    experiments::run_jacobian_coupling();
    experiments::run_super_optimal_analytical();
    experiments::run_characteristic_polynomial();
    experiments::run_predictive_validation();
    experiments::run_rho_propagation();
    experiments::run_gamma_analysis();
    experiments::run_dstar_equation();
    experiments::run_closed_form_pipeline();
    experiments::run_topology_pipeline();
    experiments::run_contraction_analysis();
    experiments::run_analytical_j2d();
    experiments::run_contraction_boundary();
    experiments::run_non_contract_test();
    experiments::run_multi_fp_analysis();
    experiments::run_boundary_conditions();
    experiments::run_nonuniform_robustness();
    experiments::run_critical_behavior();
    experiments::run_multiroot_landscape();
    experiments::run_noncontract_reconciliation();
    experiments::run_bifurcation_analysis();
    experiments::run_tau_predictive_validation();
    experiments::run_propagation_map_validation();
    experiments::run_bifurcation_curve_fit();
    experiments::run_convergence_landscape();
    experiments::run_convergence_scaling();
    experiments::run_asymptotic_limits();
    experiments::run_upper_bound_analysis();
    experiments::run_root_comparison();
    experiments::run_epsilon_sensitivity();
    experiments::run_optimal_epsilon();
    experiments::run_joint_optimization();
    experiments::run_ratio_analysis();
    experiments::run_balance_condition();
    experiments::run_optimal_regime();
    experiments::run_cross_topology_optimal();
    experiments::run_max_rho_analysis();
    experiments::run_top_concept_analysis();
    experiments::run_max_rho_minimization();
    experiments::run_joint_bottleneck_optimization();
    experiments::run_eps_asymptotic_analysis();
    experiments::run_asymptotic_constant_mapping();
    experiments::run_end_to_end_prediction();
    experiments::run_iteration_count_analysis();
    experiments::run_iteration_prediction_correction();
    experiments::run_effective_contraction_rate();
    experiments::run_full_iteration_prediction();
    experiments::run_root_top_rho_ratio();
    experiments::run_final_formula_validation();
    experiments::run_convergence_proof();
    experiments::run_full_sensitivity_analysis();
    experiments::run_lattice_convergence_rate();
    experiments::run_k_factor_analytical();
    experiments::run_distance_correction();
    experiments::run_lattice_prediction_validation();
    experiments::run_lattice_correction_refit();
    experiments::run_universal_constant_derivation();
    experiments::run_fixed_point_analysis();
    experiments::run_jacobian_spectral_structure();
    experiments::run_eigendecomposition_dynamics();
    experiments::run_lattice_coupling_model();
    experiments::run_full_lattice_prediction();
    experiments::run_error_decomposition();
    experiments::run_edge_case_stress_test();
    experiments::run_hessian_second_order();
    experiments::run_riccati_analytical_correction();
    experiments::run_eigenvector_acceleration();
    experiments::run_convergence_phase_transition();
    experiments::run_logistic_trajectory_prediction();
    experiments::run_stepwise_contraction_dynamics();
    experiments::run_fixed_point_manifold_geometry();
    experiments::run_fixed_point_sensitivity();
    experiments::run_spectral_gap_analysis();
    experiments::run_convergence_anisotropy();
    experiments::run_nonlinear_linear_transition();
    experiments::run_trajectory_reconstruction();
    experiments::run_analytical_eigenvalues();
    experiments::run_e3_structure_analysis();
    experiments::run_jacobian_sparsity_analysis();
    experiments::run_spectral_radius_from_cycles();
    experiments::run_parameter_cycle_sensitivity();
    experiments::run_cycle_landscape();
    experiments::run_cycle_topology_invariance();
    experiments::run_full_spectrum_from_cycles();
    experiments::run_dynamic_cycle_evolution();
    experiments::run_e4_cycle_decomposition();
    experiments::run_spectral_perturbation_theory();
    experiments::run_nonnormal_spectral_analysis();
    experiments::run_transient_growth_in_trajectories();
    experiments::run_eigenvector_modal_analysis();
    experiments::run_cycle_weight_pca();
    experiments::run_analytic_cycle_constraints();
    experiments::run_spectral_gap_decomposition();
    experiments::run_spectral_radius_bounds();
    experiments::run_empirical_rho_formula();
    experiments::run_spectrally_invariant_dof();
    experiments::run_invisible_dof_parameter_dependence();
    experiments::run_cross_topology_nonnormality();
    experiments::run_gmax_cycle_weight_prediction();
    experiments::run_cycle_to_spectrum_prediction();
    experiments::run_walk_decomposition();
    experiments::run_analytical_jacobian_verification();
    experiments::run_analytical_fixed_point();
    experiments::run_top_concept_spectral_radius();
    experiments::run_full_lattice_spectral_analysis();
    experiments::run_nonuniform_param_spectral();
    experiments::run_parameter_sensitivity();
    experiments::run_optimal_parameter_search();
    experiments::run_epsilon_interaction_analysis();
    experiments::run_epsilon_zero_asymptotics();
    experiments::run_iteration_count_prediction();
    experiments::run_convergence_phase_decomposition();
    experiments::run_nonlinear_acceleration_analysis();
    experiments::run_nonlinear_iteration_model();
    experiments::run_transient_amplification_analysis();
    experiments::run_lattice_size_scaling();
    experiments::run_cascade_amplification_model();
    experiments::run_cascade_interaction_model();
    experiments::run_cascade_corrected_prediction();
    experiments::run_cross_topology_prediction();
    experiments::run_large_scale_cascade_validation();
    experiments::run_cascade_refit_expanded();
    experiments::run_per_level_cascade_decomposition();
    experiments::run_nonlinearity_cascade_separation();
    experiments::run_nonuniform_cascade_validation();
    experiments::run_adaptive_cascade_correction();
    experiments::run_cycle_weight_cascade_prediction();
    experiments::run_prediction_error_structure();
    experiments::run_d0_corrected_prediction();
    experiments::run_d0_correction_generalization();
    experiments::run_d0_coefficient_analysis();
    experiments::run_analytical_d0_prediction();
}
